#include <sstream>
#include <iomanip>
#include "XYZWriter.h"
#include "../Particles/Particle.h"


void XYZWriter::writeBegin(unsigned long iteration, int numParticles) {

    std::stringstream ss;
    ss << this->filename << "_";
    ss << std::setw(3) << std::setfill('0') << iteration;
    ss << ".xyz";

    auto filenamePadded = ss.str();
    file.open(filenamePadded);

    file << numParticles << std::endl;
    file << "Generated by GraPaSim. See http://openbabel.org/wiki/XYZ_(format) for file format documentation."
         << std::endl;

// Always print numbers with decimal point
    file.setf(std::ios_base::showpoint);

}

void XYZWriter::plotParticle(const Particle &p) {

    file << "P ";
    file << p.x.x << " ";
    file << p.x.y << " ";
    file << p.x.z << " ";

    file << std::endl;
}

void XYZWriter::writeFinalize() {

    file.close();
}
